SELECT DISTINCT
    PROVIDER_BUSINESS_GROUP_NBR,
    PROVIDER_BUSINESS_GROUP_SCORE_NBR,
    PROVIDER_IDENTIFICATION_NBR,
    PRODUCT_CD,
    SERVICE_LOCATION_NBR,
    NETWORK_ID,
    RATING_SYSTEM_CD,
    EPDB_GEOGRAPHIC_AREA_CD
FROM CET_PROVIDERS
WHERE
    PROVIDER_IDENTIFICATION_NBR = 6697543
    AND NETWORK_ID = "00355"
    AND SERVICE_LOCATION_NBR = 9034514
    AND (
        SPECIALTY_CD = "90419"
        OR (
            SPECIALTY_CD IS NULL
            AND NOT EXISTS (
                SELECT 1
                FROM CET_PROVIDERS
                WHERE PROVIDER_IDENTIFICATION_NBR = 6697543
                  AND NETWORK_ID = "00355"
                  AND SERVICE_LOCATION_NBR = 9034514
                  AND SPECIALTY_CD = "90419"
            )
        )
    );
